### ISSUE TITLE
Strange behaviour of halign

### ISSUE THREAD

**Issue by z3tt** [AllanCameron/geomtextpath#101]
Hi Allan, thanks for this wonderful package! It's great to finally have a simple approach to add single labels to lines - and on top an option to make it curvy, wow!

While playing around with your package for a workshop I have noticed some strange behavior in case you have multi-line labels. It seems as it is about the slope of the line, but not sure I have completely figured it out yet.

Here is a reprex showing mutliple setups, often resulting in labels that are not aligned: 

``` r
library(ggplot2)
library(geomtextpath)

g <- 
  txhousing |> 
  dplyr::filter(year == "2000", city %in% c("Dallas", "Houston")) |> 
  ggplot(aes(x = month, y = sales, color = city, label = paste("City:\n", city)))

g + geom_textline(hjust = .1, halign = "left")
```

![](https://i.imgur.com/U94v7vV.png)

``` r
g + geom_textline(hjust = .1, halign = "right")
```

![](https://i.imgur.com/CgHnD48.png)

``` r

g + geom_textline(hjust = .4, halign = "left")
```

![](https://i.imgur.com/ICV65Oz.png)

``` r
g + geom_textline(hjust = .4, halign = "right")
```

![](https://i.imgur.com/RBMOeaV.png)

``` r

g + geom_textline(hjust = .9, halign = "left")
```

![](https://i.imgur.com/BtnK2U6.png)

``` r
g + geom_textline(hjust = .9, halign = "right")
```

![](https://i.imgur.com/hS4dRWx.png)

<sup>Created on 2023-11-01 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

Maybe you know why this is happening and how to fix it?

**Comment by teunbrand** [comment]
It makes it somewhat better if you use `paste0()` instead of `paste()` to avoid the space in front of Houston/Dallas, but sometimes the normal to a curve is unlucky in terms of text placement.

**Comment by z3tt** [comment]
Thanks @teunbrand, you are absolutely right about `paste0`. However, I am pretty sure that this is not the main cause here as we also see misalignment at the end of the words (cf 2nd and 4th example plot). Any chance to fix this or is it impossible due to the individual properties of the curve and placement?

**Comment by teunbrand** [comment]
This seems very curve dependant to me, but because you have a modest-width label, you might get away with setting `straight = TRUE` without it being too noticeable. This should just calculate one angle for the text so that you don't get weird curvatures interfering with alignment.

**Comment by teunbrand** [comment]
Another option is to use `text_smoothing = 25` or so to get rid of the sharpest irregularities.
