### ISSUE TITLE
Add compatibility with `ggbump`

### ISSUE THREAD

**Issue by JDenn0514** [AllanCameron/geomtextpath#109]
Hi! Would it be possible to add the statistical transformation created in [ggbump](https://github.com/davidsjoberg/ggbump), called `StatBump`, so that we can use `geom_textpath` and `geom_textline` with bump plots?

This is a really simple enhancement as all of the code necessary for this was already created in David Sjoberg's [ggbump](https://github.com/davidsjoberg/ggbump) package. First, you simply add:
 ```
importFrom ggbump rank_sigmoid sigmoid
```
to the file geomtextpath-package.R. Then, you have to add a new script creating the StatBump transformation. This is found inside the [geom_bump.R](https://github.com/davidsjoberg/ggbump/blob/master/R/geom_bump.R) file in the ggbump package. For ease I have also pasted it below:
```r
#' @export
#' @format NULL
#' @usage NULL

StatBump <- ggplot2::ggproto(
  "StatBump", ggplot2::Stat,
  setup_data = function(data, params) {
    # Create x_lag, and y_lag to be passed to `compute_group`
    # Factors need this to be able to compute a sigmoid function
    data <- data %>%
      dplyr::mutate(r = dplyr::row_number()) %>%
      dplyr::arrange(x) %>%
      dplyr::group_by_at(vars(-PANEL, -group, -x, -y, -r)) %>%
      dplyr::mutate(x_lag = dplyr::lag(x),
                    y_lag = dplyr::lag(y)) %>%
      dplyr::ungroup() %>%
      dplyr::arrange(r) %>%
      dplyr::select(-.data$r) %>%
      as.data.frame()
    data
  },
  compute_group = function(data, scales, smooth = 8, direction = "x") {
    data <- data %>%
      dplyr::arrange(x)

    # Handling of the special case of factors
    # Factors come as a df with one row
    if(nrow(data) == 1) {
      if(is.na(data$x_lag) | is.na(data$y_lag)) {
        return(data %>% dplyr::slice(0))
      } else {
        out <- sigmoid(data$x_lag, data$x, data$y_lag, data$y,
                       smooth = smooth, direction = direction)
        return(as.data.frame(out))
      }
    }

    # Normal case
    out <-rank_sigmoid(data$x, data$y, smooth = smooth, direction = direction) %>%
      dplyr::mutate(key = 1) %>%
      dplyr::left_join(data %>%
                         dplyr::select(-x, -y) %>%
                         dplyr::mutate(key = 1) %>%
                         dplyr::distinct(),
                       by = "key") %>%
      dplyr::select(-key) %>%
      as.data.frame()
    out
  },

  required_aes = c("x", "y")
)

```

I have also forked your package and done this already. You can see that the only differences between my package and yours is the additions mentioned here. I also tested it and it worked. Here is a graph I made using ggbump, gghighlight and my forked version of geomtextpath:

![artist23](https://github.com/AllanCameron/geomtextpath/assets/80338305/4fc0ecae-705d-4088-9ca6-f862c05e5905)

**Comment by teunbrand** [comment]
Yeah I agree with Allan's approach here. I put in a PR to ggbump specifically for this usecase as well: https://github.com/davidsjoberg/ggbump/issues/20.
