### ISSUE TITLE
geomtextpath example code does not seem to work

### ISSUE THREAD

**Issue by davidhodge931** [AllanCameron/geomtextpath#114]
This code used to work.. So maybe this relates to the ggplot2 update?

``` r
library(tidyverse)
library(geomtextpath)

expand.grid(x = 1:nrow(volcano), y = 1:ncol(volcano)) |> 
  mutate(z = c(volcano)) |> 
  ggplot(aes(x = x, y = y, z = z)) +
  geom_contour_filled() +
  geom_textcontour(aes(label = after_stat(level)))
#> Error in `geom_textcontour()`:
#> ! Problem while converting geom to grob.
#> ℹ Error occurred in the 2nd layer.
#> Caused by error in `txt$shape[, shape_vars]`:
#> ! Can't subset columns that don't exist.
#> ✖ Column `x_midpoint` doesn't exist.
```

<sup>Created on 2024-04-17 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>
```

**Comment by JiazhouWang** [comment]
SAME. 

                  Package    Version
abind               abind      1.4-5
backports       backports      1.4.1
bit                   bit      4.0.5
bit64               bit64      4.0.5
brio                 brio      1.1.4
broom               broom      1.0.5
callr               callr      3.7.3
car                   car      3.1-2
carData           carData      3.0-5
caret               caret     6.0-94
cellranger     cellranger      1.1.0
cli                   cli      3.6.2
clipr               clipr      0.8.0
clock               clock      0.7.0
colorspace     colorspace      2.1-0
corrplot         corrplot       0.92
cowplot           cowplot      1.1.2
cpp11               cpp11      0.4.7
crayon             crayon      1.5.2
data.table     data.table    1.14.10
desc                 desc      1.4.3
diagram           diagram      1.6.5
diffobj           diffobj      0.3.5
digest             digest     0.6.33
dplyr               dplyr      1.1.4
e1071               e1071     1.7-14
egg                   egg      0.4.5
ellipsis         ellipsis      0.3.2
evaluate         evaluate       0.23
fansi               fansi      1.0.6
farver             farver      2.1.1
foreach           foreach      1.5.2
fs                     fs      1.6.3
future             future     1.33.1
future.apply future.apply     1.11.1
generics         generics      0.1.3
geomtextpath geomtextpath      0.1.3
ggarchery       ggarchery      0.4.3
ggplot2           ggplot2      3.5.1
ggpubr             ggpubr      0.6.0
ggrepel           ggrepel      0.9.4
ggsci               ggsci      3.0.0
ggsignif         ggsignif      0.6.4
globals           globals     0.16.2
glue                 glue      1.6.2
gower               gower      1.0.1
gridExtra       gridExtra        2.3
gtable             gtable      0.3.4
hardhat           hardhat      1.3.0
hms                   hms      1.1.3
ipred               ipred     0.9-14
isoband           isoband      0.2.7
iterators       iterators     1.0.14
jsonlite         jsonlite      1.8.8
labeling         labeling      0.4.3
lava                 lava      1.7.3
lifecycle       lifecycle      1.0.4
listenv           listenv      0.9.0
lme4                 lme4   1.1-35.1
lubridate       lubridate      1.9.3
magrittr         magrittr      2.0.3
MatrixModels MatrixModels      0.5-3
minqa               minqa      1.2.6
ModelMetrics ModelMetrics    1.2.2.2
munsell           munsell      0.5.0
nloptr             nloptr      2.0.3
numDeriv         numDeriv 2016.8-1.1
parallelly     parallelly     1.36.0
pbkrtest         pbkrtest      0.5.2
pillar             pillar      1.9.0
pkgbuild         pkgbuild      1.4.3
pkgconfig       pkgconfig      2.0.3
pkgload           pkgload      1.3.3
plyr                 plyr      1.8.9
polynom           polynom      1.4-1
praise             praise      1.0.0
prettyunits   prettyunits      1.2.0
pROC                 pROC     1.18.5
processx         processx      3.8.3
prodlim           prodlim 2023.08.28
progress         progress      1.2.3
progressr       progressr     0.14.0
proxy               proxy     0.4-27
ps                     ps      1.7.5
purrr               purrr      1.0.2
quantreg         quantreg       5.97
R6                     R6      2.5.1
RColorBrewer RColorBrewer      1.1-3
Rcpp                 Rcpp     1.0.11
RcppEigen       RcppEigen  0.3.3.9.4
readr               readr      2.1.5
readxl             readxl      1.4.3
recipes           recipes      1.0.9
rematch           rematch      2.0.0
rematch2         rematch2      2.1.2
renv                 renv      1.0.3
reshape           reshape      0.8.9
reshape2         reshape2      1.4.4
rlang               rlang      1.1.2
rprojroot       rprojroot      2.0.4
rstatix           rstatix      0.7.2
scales             scales      1.3.0
shape               shape      1.4.6
SparseM           SparseM       1.81
SQUAREM           SQUAREM     2021.1
stringi           stringi      1.8.3
stringr           stringr      1.5.1
systemfonts   systemfonts      1.1.0
testthat         testthat      3.2.1
textshaping   textshaping      0.4.0
tibble             tibble      3.2.1
tidyr               tidyr      1.3.0
tidyselect     tidyselect      1.2.0
timechange     timechange      0.2.0
timeDate         timeDate   4032.109
tzdb                 tzdb      0.4.0
utf8                 utf8      1.2.4
vctrs               vctrs      0.6.5
viridisLite   viridisLite      0.4.2
vroom               vroom      1.6.5
waldo               waldo      0.5.2
withr               withr      2.5.2

**Comment by teunbrand** [comment]
This is probably due to #116, which would be fixed by #117.
You can try to see if that PR works by using `pak::pak("AllanCameron/geomtextpath#117")`

**Comment by rsiani** [comment]
Doesn't seem to work for me

```
pak::pak("AllanCameron/geomtextpath#117")
Error:                                                                    
! error in pak subprocess
Caused by error: 
! Could not solve package dependencies:
* AllanCameron/geomtextpath#117: ! pkgdepends resolution error for AllanCameron/geomtextpath#117.
Caused by error: 
! no such index at level 5

Type .Last.error to see the more details.
.Last.error
<callr_error/rlib_error_3_0/rlib_error/error>
Error: 
! error in pak subprocess
Caused by error: 
! Could not solve package dependencies:
* AllanCameron/geomtextpath#117: ! pkgdepends resolution error for AllanCameron/geomtextpath#117.
Caused by error: 
! no such index at level 5

---
Backtrace:
1. pak::pak("AllanCameron/geomtextpath#117")
2. pak::pkg_install(pkg, ...)
3. pak:::remote(function(...) get("pkg_install_make_plan", asNamespace("pak"))(...), …
4. err$throw(res$error)
---
Subprocess backtrace:
1. base::withCallingHandlers(cli_message = function(msg) { …
2. get("pkg_install_make_plan", asNamespace("pak"))(...)
3. prop$stop_for_solution_error()
4. private$plan$stop_for_solve_error()
5. pkgdepends:::pkgplan_stop_for_solve_error(self, private)
6. base::throw(new_error("Could not solve package dependencies:\n", msg, …
7. | base::signalCondition(cond)
8. global (function (e) …
#> Error: <text>:3:9: unexpected 'in'
#> 2: Error:                                                                    
#> 3: ! error in
#>            ^
```

Created on 2024-05-29 with [reprex v2.1.0](https://reprex.tidyverse.org/)

**Comment by JiazhouWang** [comment]
SAME

**Comment by teunbrand** [comment]
Does `remotes::install_github("AllanCameron/geomtextpath", quiet = TRUE)` fail as well?

**Comment by rsiani** [comment]
I managed to get it to work after installing again "AllanCameron/geomtextpath" and also textshaping 0.4.0

**Comment by teunbrand** [comment]
This should currently work again
