### ISSUE TITLE
Release geomtextpath 0.1.4

### ISSUE THREAD

**Issue by teunbrand** [AllanCameron/geomtextpath#119]
Prepare for release:

* [x] `git pull`
* [x] Check [current CRAN check results](https://cran.rstudio.org/web/checks/check_results_geomtextpath.html)
* [x] [Polish NEWS](https://style.tidyverse.org/news.html#news-release)
* [x] `usethis::use_github_links()`
* [x] `urlchecker::url_check()`
* [x] `devtools::build_readme()`
* [x] `devtools::check(remote = TRUE, manual = TRUE)`
* [x] `devtools::check_win_devel()`
* [x] `revdepcheck::revdep_check(num_workers = 4)`
* [x] Update `cran-comments.md`
* [x] `git push`

Submit to CRAN:

* [x] `usethis::use_version('patch')`
* [x] `devtools::submit_cran()`
* [x] Approve email

Wait for CRAN...

* [x] Accepted :tada:
* [x] `usethis::use_github_release()`
* [x] `usethis::use_dev_version(push = TRUE)`

**Comment by teunbrand** [comment]
@AllanCameron I just need you to approve the submission via email, could you check the box when that is done?

**Comment by AllanCameron** [comment]
Thanks Teun

I have confirmed the e-mail

**Comment by AllanCameron** [comment]
We've failed a test on Debisn - I'll submit a fix today

**Comment by teunbrand** [comment]
Thanks for picking this up, I can't know what CRAN communicated

**Comment by teunbrand** [comment]
Thanks Allan for fixing the final part!

**Comment by AllanCameron** [comment]
Thank you Teun. Unfortunately I have been unwell and in hospital recently, so have been unable to sort most of this out. I do appreciate all your quick fixes. I am on the mend now!

**Comment by teunbrand** [comment]
I'm sorry to hear that Allan though I'm glad you're on the mend. I wish you well and hope for a speedy recovery.
If it can help offload some mental burder, I wouldn't mind taking over as maintainer the next time an issue pops up, until some time you see fit.

**Comment by AllanCameron** [comment]
Thanks Teun. That's very kind of you, but I am back to full strength now, so hope to engage a bit more in the maintenance.  

As an aside, it was nice to see we got a couple of citations in _Nature Communications_ ([here](https://www.nature.com/articles/s41467-024-49080-9) and [here](https://www.nature.com/articles/s41467-024-48324-y) ). It makes me wonder whether we should have a canonical publication to cite, even if it is in a small low-impact journal? I never really thought that a visualization package would gather citations (as opposed to a statistical package), but it might be a nice little addition to the CV. This is something I might look into if it interests you?

**Comment by teunbrand** [comment]
Yeah I definitely think having a publication would be a good idea. Maybe [JOSS](https://joss.theoj.org/) might be an appropriate place to publish? It was the first place that came to mind, there might be other suitable places as well.

In addition, CRAN is now in the process of giving out DOIs for packages so there will be a persistent identifier people can cite in the future.
