### ISSUE TITLE
0.1.4 release line breaks not working

### ISSUE THREAD

**Issue by ulysses822** [AllanCameron/geomtextpath#121]
The 0.1.4. release has reintroduced the issue around line breaks not working (#4 )

Using the same reprex as in the previous issue
```
library(ggplot2)
library(geomtextpath)

df <- data.frame(x = 1:1000, y = 1, z = "This is a perfectly\nflat label")

ggplot(df, aes(x, y, label = z)) +
  geom_textpath(size = 6, linewidth = 0)
```

in the 0.1.4 release, this code generates
![image](https://github.com/AllanCameron/geomtextpath/assets/52043871/d4841c87-19f3-4ad7-8de9-2170cf1fb7d7)

Using the previous release (0.1.3) and the 0.3.7 release of `textshaping`, the same code generates the correct output
![image](https://github.com/AllanCameron/geomtextpath/assets/52043871/77f1edac-9580-4dee-bf2f-606b0a8aa918)

Digging into it a bit, I'm fairly sure the issue is with the `textshaping package`. With the following example
```
txt <- "This is a perfectly\nflat label"

shape <- textshaping::shape_text(txt)
unique(shape$shape$y_offset)
```
All the glyphs have the same y_offset despite the linebreak in the text. Whereas with the 0.3.7 release of `textshaping`, the y_offsets are what would be expected (two diffferent offset values corresponding to the two different lines of text).

**Comment by AllanCameron** [comment]
Yes, we decided to "outsource" line breaks to textshaping at an early stage of development to avoid reinventing the wheel. Textshaping now seems to ignore line breaks, which means geomtextpath does too. Our two options are to implement line breaks manually (this is certainly possible but will require a bit of effort), or submit a bug report to {{textshaping}}. I think I will try the second option first.

**Comment by teunbrand** [comment]
This should work again with the new release of {textshaping}.

``` r
library(ggplot2)
library(geomtextpath)
packageVersion("textshaping")
#> [1] '0.4.1'

df <- data.frame(x = 1:1000, y = 1, z = "This is a perfectly\nflat label")

ggplot(df, aes(x, y, label = z)) +
  geom_textpath(size = 6)
```

![](https://i.imgur.com/65iEUUn.png)

<sup>Created on 2024-12-10 with [reprex v2.1.1](https://reprex.tidyverse.org)</sup>
