### ISSUE TITLE
Add linear regression formula along regression line with geom_textsmooth

### ISSUE THREAD

**Issue by kotliary** [AllanCameron/geomtextpath#122]
Is it possible to add the regression formula (and probably other metrics) along the line? 
For example, in [ggpubr](https://rpkgs.datanovia.com/ggpubr/reference/stat_regline_equation.html#computed-variables-1) the formula can be extracted with `..eq.formula..` and mapped to the label.

Something like this:

```r
geom_textsmooth(
    aes(label =  paste(..eq.label.., ..adj.rr.label.., sep = "~~~~")),
    method = "lm", formula = formula
  )
```

**Comment by AllanCameron** [comment]
Thanks for posting. I don't think this is something we would plan to add to geomtextpath. My view is that regression equation geoms are essentially just convenience functions that allow you to add annotations to your plot with a few less lines of code. They can easily be added along lines in geomtextpath by precalculating them
```r
library(tidyverse)
library(geomtextpath)

iris %>%
  nest(data = -Species) %>%
  mutate(grad = map(data, ~ coef(lm(Petal.Width ~ Petal.Length, data = .x))),
         incpt = map(grad, ~ round(.x[1], 2)),
         grad = map(grad, ~ round(.x[2], 2))) %>%
  unnest(cols = c(data, incpt, grad)) %>%
  mutate(label = paste0("y = ", grad, "x + ", incpt)) %>%
  ggplot(aes(Petal.Length, Petal.Width, colour = Species)) +
  geom_point(alpha = 0.2) +
  geom_textsmooth(method = "lm", aes(label = label), fullrange = TRUE,
                   textcolour = "black", vjust = -0.5) +
  theme_minimal(16)
```
![image](https://github.com/user-attachments/assets/eef32350-85e1-4061-9e99-76df53ebd09a)

There are many extension packages that aim to make doing common tasks a little easier with such convenience functions, but they often lack flexibility (try getting ggpubr to do a polynomial lm for example), and we're not able to include all the useful stat transforms from other extension packages.

As long as the extensions are written in a standard fashion it is possible to get them to play nicely with each other. In the case of geomtextpath and ggpubr, you could combine their features by defining a `geom_textregline` function in your own code as follows
```r
library(geomtextpath)
library(ggpubr)

geom_textregline <- function(...) {
  structure(rlang::list2(...), class = "textreg")
}

ggplot_add.textreg <- function(object, plot, object_name = "textreg") {
  regdat <- ggplot_build(plot + ggpubr::stat_regline_equation())$data
  regdat <- regdat[[length(regdat)]]
  layerdat <- cbind(plot$data, regdat)
  
  plot + do.call(geom_textsmooth, c(list(data = layerdat), object))
}
```
Which then allows 
```r
ggplot(mtcars, aes(cyl, mpg)) +
  geom_point(color = "lightblue", size = 4) + 
  geom_textregline(aes(label = paste(label, adj.rr.label, sep = "~~~~")), 
                   formula = y ~ x, method = "lm", parse = TRUE, 
                   vjust = -0.5, size = 5, hjust = 0.15) +
  theme_minimal(16)
```
![image](https://github.com/user-attachments/assets/c065ce60-e07b-4ec0-88ed-7cd3cf53ceb4)

Hopefully there's enough here to allow you to create the plots you want.
