### ISSUE TITLE
coord_curvedpolar

### ISSUE THREAD

**Issue by AllanCameron** [AllanCameron/geomtextpath#21]
I have developed a new coord, though it still needs documented and tested before I commit the changes. Effectively, it uses textpath grobs for axis labels:
``` r
p <- ggplot(data.frame(x = paste("Category label", 1:5), y = runif(5)), 
            aes(x, y, fill = x)) +
       geom_col() +
       theme_bw() +
       theme(panel.border = element_blank(),
             legend.position = "none")

p
```
![image](https://user-images.githubusercontent.com/33987720/143791701-1bf6e1a2-66d9-450c-a406-a522623cd6b8.png)

``` r
p + coord_polar()
```
![image](https://user-images.githubusercontent.com/33987720/143791722-17368989-118a-44fa-af3f-99576bcc27a9.png)

``` r
p + coord_curvedpolar()
```
![image](https://user-images.githubusercontent.com/33987720/143791740-ed6cdfab-3c04-43f0-9b12-1a4c1d9356d0.png)

``` r
 p + coord_curvedpolar() + 
       theme(textpath.axis.text = element_textpath(color = "blue4", size = 15))
```
![image](https://user-images.githubusercontent.com/33987720/143791900-720aa991-a4c8-4f72-aeb8-2e72cec91e85.png)

Is this something we're both happy to incorporate in the package? I think it improves the look of the native polar coordinate labels considerably. Not sure about what to call it though.

**Comment by teunbrand** [comment]
Hi Allan, yes looks like a good addition to the package. Putting the labels on a curve looks much more elegant that the default labelling. One thing to keep in mind is that if we introduce an `element_textpath()`, it is unclear whether it should be a stand-in for `element_line()` or `element_text()` and I think people expect that it would work anywhere, not just in this coord function.

**Comment by AllanCameron** [comment]
I think it would be nice if we could use an `element_textpath` as a substitution for `element_text`, and I think it should be possible to get this to work. It might be a challenge to get it to work as demonstrated above as _purely_ an element without the need for a whole new `coord`, but it would be nice if we could.

One of the difficulties is that the `textpathGrob` needs to be passed path data, and of course `element_text` only contains single points. It is possible to create a simple horizontal path from these points inside `element_grob.element_textpath`, but in polar co-ordinates this step has to occur _after_ the polar transformation, so we need to calculate the correct circular path. If the co-ordinates aren't polar, this creates some funky results. If we can get `element_grob.element_textpath` to be know the co-ordinate system, then there's no reason why we can't have `element_textpath` as a drop-in for `element_text`

**Comment by teunbrand** [comment]
I'm pretty confident that we can get `element_textpath()` to work, instead, the point I'm raising is whether we should. If it is for a single use case such as `coord_curvedpolar()`, it is a bit of a burden on users to have to recall that it should not be `element_text()` and that the axis text in this particular coord has a different theme element that controls the axis text. We can internally use the result of `calc_element("axis.text.{x/y}", theme)` to populate the text parameters and not go through `element_grob()`, but construct the textpath ourselves (I'm presuming in this case we don't have a path component to render as well). I think it would be nice if `+ theme(axis.text.{x/y} = element_text(colour = "blue"))` would just work out of the box.

**Comment by AllanCameron** [comment]
That sounds like a good plan. I did not know about `calc_element`. Presumably we can use this in the `draw_fg` member function to convert the `element_text` parameters into appropriate arguments for the `textpathGrob`. I will try this approach.

**Comment by AllanCameron** [comment]
OK, so I managed to put everything inside the `render_fg` function, including your trick of harvesting the gpars from `element_text`. The only slight snag is that `halign` isn't a parameter within `element_text`, and has to be passed as a parameter of the `coord_curvedpolar` function itself. This is only relevant for multi-line axis labels anyway, which should be pretty uncommon.

The amazing thing is how easy all this is to implement now that we have a solid `textpathGrob`

The current behavior is this:
``` r
library(geomtextpath)
#> Loading required package: ggplot2

p <- ggplot(data.frame(x = paste("Category label", 1:5), y = runif(5)), 
            aes(x, y, fill = x)) +
       geom_col() +
       theme_bw() +
       theme(panel.border = element_blank(),
             legend.position = "none", 
             axis.text.x = element_text(size = 10, vjust = 0.5))

p 
```

![](https://i.imgur.com/0zJETCt.png)

``` r
p + coord_polar()
```

![](https://i.imgur.com/iMUhjrB.png)

``` r
p + coord_curvedpolar()
```

![](https://i.imgur.com/P3QjJNa.png)

``` r
p + coord_curvedpolar() + 
  theme(axis.text.x = element_text(color = "red4", size = 15, hjust = 1))
```

![](https://i.imgur.com/x7IAXrG.png)

<sup>Created on 2021-11-29 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

**Comment by teunbrand** [comment]
Very nice work Allan! I think with all the nice examples and this new function, we could dedicate a separate vignette to curved text in polar coordinates. I'll play around with this later this evening to see how it works.

**Comment by AllanCameron** [comment]
My impression from reading the docs and the internals is that Hadley doesn't like polar plots very much.  I understand his reluctance, but I do think they have a place.  It almost feels like `coord_polar` has been implemented grudgingly. The theta axis that we change here is actually just drawn as a foreground layer that calculates some grobs. I have lifted most of the code from `CoordPolar`, and only changed which grobs are drawn.

I don't think the `hjust` and `vjust` are correct at the moment. I think this is because of the direction that the supporting segments are drawn in. Hopefully this is an easy fix.

**Comment by AllanCameron** [comment]
Ah, I think I've found a problem. The `vjust` flips when `flip_inverted` is `TRUE`, which I don't think is the correct behaviour (and actually makes it much harder to have `vjust` - able axis labels. I will submit a fix for this.

**Comment by teunbrand** [comment]
Right yes, that makes sense. I think it might just be as easy as to add this:

```{r}
attr(label, "offset") <- 0 - attr(label, "offset")
```
to the following lines:

https://github.com/AllanCameron/geomtextpath/blob/a4075faf259130c7cb2d489c672d475ad61d5a34/R/geometry_helpers.R#L136-L142

**Comment by AllanCameron** [comment]
OK, I'll try that

**Comment by teunbrand** [comment]
Should we just avoid flipping `hjust` then, if flipping it can give these weird results? Or should we defensively code against these cases? Is there a case where flipping `hjust` is sensible?

**Comment by AllanCameron** [comment]
If you remove the hjust flip, the surrounding line flips too, so the text still gets scored out, but on the other side.

**Comment by teunbrand** [comment]
Right yes, you're correct. I found a 2-line fix for this, I'll include in the next PR.
