### ISSUE TITLE
Parameter names

### ISSUE THREAD

**Issue by teunbrand** [AllanCameron/geomtextpath#42]
Hi Alan,

I was thinking about these parameters we've introduced and whether there might be a more convenient way to pass them around. This made me think that now would be a good time to review the names of the parameters. The timing seems about right, because we've not written too many geoms yet such that this would be a huge burden, and we've no responsibility yet to users that these names remain stable. Some of them are quite long, so I thought of the following alternatives.

### `include_line`
* `path`
* `draw_path`
* `text_only` (need to flip TRUE/ FALSE then)

### `cut_path`
* ~~`trim`~~ (would have conflict with the density stat's trim parameter)
* `trim_path`
* `bite`, because we're taking a 'bite' from the path where the text should be
* `bite_path`

### `flip_inverted`
* `flip`
* `autoflip`
* `upright`

### `halign`
I think this is fine and have no better alternatives

### `offset`
I think this is a fine name, but is confusing because we're using offset in two ways in our code, once as this parameter, which is just to pass a `unit` object to `vjust`, and once for actual path offsets.
* `vadjust` for vertical adjustment
* `oadjust` for an adjustment orthogonal to the direction of the text
* `ort_adj`

### `keep_straight`
* `straight`
* `straight_text`
* `straighten`
* `curve_text` (flip the meaning of TRUE/FALSE)
* `bend_text` " "

I'm curious to hear your thoughts and wonder if you might have some suggestions of your own!

**Comment by AllanCameron** [comment]
Hi Teun. I'm glad you brought this up. I think now is a good time to think about renaming. I had previously got into the habit of putting periods before functions I didn't want to export, but this isn't really helpful within the roxygen ecosystem, and sometimes proves an annoyance, so we should probably remove the periods.

For the parameter names you mentioned, my thoughts are
 - `include_line` -> `text_only` (needs flipped logically)
 - `cut_path` -> `gap` (short and doesn't need flipped logically)
 - `flip_inverted` -> `upright`
 - `offset` -> I think I'd keep this but maybe change the variable name to something else, like `offset_paths`
 - `keep_straight` -> `straight`

**Comment by teunbrand** [comment]
> putting periods before functions

I think this works for functions that you want to export but not expose. I think the typical way to indicate a function is internal is to declare the following in the roxygen comments:
``` r
#' @keywords internal
```

> cut_path -> gap (short and doesn't need flipped logically)

This is nice and better than what I could come up with.

> I think now is a good time to think about renaming

There are indeed some function in the package that have changed meaning over the course of development. I think `.get_path_points()` doesn't really get points on a path but it places the text, so maybe a better name might be `place_text()`? Perhaps `.get_surrounding_lines()` could be `make_gap()`? Any functions you'd like to mark for renaming?

**Comment by AllanCameron** [comment]
I don't really see the value of roxygen comments for non-exported functions. If no docs are built, then standard comments to help with maintenance and debugging should be adequate. It's reasonable to preface them with roxygen tags to help package building of course.

**Comment by AllanCameron** [comment]
I agree with your suggestions for `.get_path_points` and `.get_surrounding_lines`. I had wondered if the file name `geometry_helpers.R` had become a bit inaccurate too, but I can't really think of anything more appropriate at the moment.

**Comment by teunbrand** [comment]
Yes good point. I think splitting them out to `text_placement.R` and `path_handling.R` or something might be better. The `path_handling.R` file can also get the `dedup_path`, `pathify`, `prepare_path` and `.add_path_grob` functions.

**Comment by teunbrand** [comment]
I'll go and rename some of the parameters according to the suggestions, and maybe split the `geometry_helpers.R` file.

**Comment by teunbrand** [comment]
I think we can close this for now
