### ISSUE TITLE
`vjust` is not respected on linux

### ISSUE THREAD

**Issue by albert-ying** [AllanCameron/geomtextpath#55]
Hi, thank you for this amazing package! I noticed that for some reason the `geomtextpath` doesn't respond to `vjust` value on my linux machine. This bug doesn't appear on my macOS machine tho

Here is the code I copyed from a previous issue
```
library(ggplot2)
library(geomtextpath)
library(patchwork)

df <- data.frame(
  x = seq(-0.5, 1.5, length.out = 10),                                       
  y = 1,
  label = "geom_textpath"
)

plot_vjust <- function(vjust) {
  ggplot(df, aes(x, y)) +
    geom_textpath(aes(label = label), vjust = vjust) +                       
    annotate(x = 2, y = 1, label = "geom_text", geom = "text", vjust = vjust) +
    ggtitle(paste0("vjust = ", vjust)) +                                     
    scale_x_continuous(limits = c(-1, 3))                                    
}

p = plot_vjust(-1) + plot_vjust(0) + plot_vjust(1) + plot_vjust(2) + plot_vjust(10) + plot_vjust(15)

```

And this is my output on Linux machine: you can see the `geom_textpath` does not respond to `vjust` value like `geom_text`

<img width="903" alt="image" src="https://user-images.githubusercontent.com/59846322/149353269-f133d0f4-4568-49e0-ab28-fd407781bf05.png">

Here is my sessionInfo

```
R version 4.1.1 (2021-08-10)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 16.04.6 LTS

Matrix products: default
BLAS/LAPACK: /usr/lib/libopenblasp-r0.2.18.so

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=en_US.UTF-8       
  [4] LC_COLLATE=en_US.UTF-8     LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
   [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                  LC_ADDRESS=C              
   [10] LC_TELEPHONE=C             LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

   attached base packages:
   [1] stats     graphics  grDevices utils     datasets  methods   base     

   other attached packages:
   [1] patchwork_1.1.1    geomtextpath_0.1.0 ggplot2_3.3.5     

   loaded via a namespace (and not attached):
    [1] Rcpp_1.0.7             magrittr_2.0.1         tidyselect_1.1.1      
     [4] munsell_0.5.0          colorspace_2.0-2       R6_2.5.1              
      [7] ragg_1.2.1             rlang_0.4.12           fansi_0.5.0           
      [10] dplyr_1.0.7            tools_4.1.1            grid_4.1.1            
      [13] gtable_0.3.0           utf8_1.2.2             DBI_1.1.2             
      [16] withr_2.4.3            systemfonts_1.0.3.9000 ellipsis_0.3.2        
      [19] digest_0.6.28          assertthat_0.2.1       tibble_3.1.5          
      [22] lifecycle_1.0.1        crayon_1.4.2           textshaping_0.3.6     
      [25] farver_2.1.0           purrr_0.3.4            vctrs_0.3.8           
      [28] glue_1.4.2             labeling_0.4.2         compiler_4.1.1        
      [31] pillar_1.6.4           generics_0.1.0         scales_1.1.1          
      [34] pkgconfig_2.0.3    
```

Thank you!

**Comment by AllanCameron** [comment]
Hi @albert-ying. Thanks for using the package, and bringing this to our attention. It's not clear to me why this bug would show up on one system and not another. I'm assuming you have tried a new R session and the latest development version of `geomtextpath`?

If so, would you mind checking the behaviour of a slightly modified version of the code so  that we can try to track this down? If you modify the function to
``` r
plot_vjust <- function(vjust) {
  ggplot(df, aes(x, y)) +
    geom_textpath(aes(label = label, vjust = vjust)) +                       
    geom_text(x = 2, y = 1, label = "geom_text", vjust = vjust) +
    ggtitle(paste0("vjust = ", vjust)) +                                     
    scale_x_continuous(limits = c(-1, 3)) + 
    scale_vjust_identity()                                  
}
```
Do you still get the same behaviour?

**Comment by albert-ying** [comment]
> I'm assuming you have tried a new R session and the latest development version of `geomtextpath`

Yes.

I tried your modified code, it gives me the same result.

I noticed that when I save the plot as PDF, it gives the weird-looking font

<img width="899" alt="image" src="https://user-images.githubusercontent.com/59846322/149368362-6bb368c4-72fc-4cc5-b158-d84485786831.png">

Might be related to the rendering of the text/font?

**Comment by AllanCameron** [comment]
Thanks for trying that Albert. It looks to me as though the spacing is being increased between letters in the pdf version until you specify "family". Ultimately, both versions are drawn with the same font using `grid::textGrob` - I'm guessing that the pdf device has a different fallback font when the "family" is left blank. We'll need to investigate this further, along with the vjust issue.

Thanks again

**Comment by teunbrand** [comment]
Strange, I get the following on Linux, where the textpath does seem responsive to `vjust`. My R version is 4.0.5 and linux distro is Ubuntu 20.04.3.

``` r
library(ggplot2)
library(geomtextpath)
library(patchwork)

df <- data.frame(
  x = seq(-0.5, 1.5, length.out = 10),                                       
  y = 1,
  label = "geom_textpath"
)

plot_vjust <- function(vjust) {
  ggplot(df, aes(x, y)) +
    geom_textpath(aes(label = label), vjust = vjust) +                       
    annotate(x = 2, y = 1, label = "geom_text", geom = "text", vjust = vjust) +
    ggtitle(paste0("vjust = ", vjust)) +                                     
    scale_x_continuous(limits = c(-1, 3))                                    
}

p = plot_vjust(-1) + plot_vjust(0) + plot_vjust(1) + plot_vjust(2) + plot_vjust(10) + plot_vjust(15)
p
```

![](https://i.imgur.com/jNXUwue.png)

<sup>Created on 2022-01-13 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

But something seems off about vjust anyhow, it doesn't quite follow the vanilla text offsets.

**Comment by albert-ying** [comment]
Hmm I'm on R 4.1.1, Ubuntuk 16.04.6.

Is there any system-related dependency that might be related to this?

**Comment by teunbrand** [comment]
Yeah I defensively coded against that bug previously:
https://github.com/AllanCameron/geomtextpath/blob/616d6b5cb6babfec835a63504bec146cb3633401/R/text_helpers.R#L44-L45
But this I forgot to catch that bug when I refactored the code at some point. AFAIK, it shouldn't affect any other vjust values.

**Comment by albert-ying** [comment]
Here is my output, the ymin indeed does not vary

```
geomtextpath:::measure_label("AB\nCD")[[1]]
  glyph       ymin        xmin       xmid      xmax substring y_id
1     A 0.07736545 0.008029514 0.06488715 0.1217448         1    2
2     B 0.07736545 0.121961806 0.17903646 0.2361111         1    2
3     C 0.07736545 0.000000000 0.05815972 0.1163194         1    2
4     D 0.07736545 0.116319444 0.18033854 0.2443576         1    2
```

**Comment by teunbrand** [comment]
Thanks! That narrows it down to a particular part of the code.

**Comment by AllanCameron** [comment]
Is this perhaps a problem with `textshaping::shape_text` not respecting vjust on some machines?


@albert-ying -In a fresh R session with your normal default settings, the following function will return the value of the y offset (in pixels) for different values of vjust, given default font values:
```r
 f <- function(x) textshaping::shape_text('x', vjust = x)$shape$y_offset
```
For example, I get
``` r
f(0)
#> [1] 0

f(0.5)
#> [1] -5.421875
```
The symptoms you describe suggest that there is a problem with `textshaping::shape_text` (or the arguments passed to it) that would result in this function returning 0 for any input.

If I am right about this, then it suggests that on your system, every glyph height is somehow being measured as 0. This would happen, for example, if you passed a font size of 0, or if your device height was 0. We know that the font size is not 0, since the x measurements are correct. The most likely cause I can see for this is that the device height is somehow being registered as 0 in the `textshaping::shape_text` function, but only if the `f()` function above returns 0 for all numeric inputs.

**Comment by albert-ying** [comment]
Yes, you are right! @AllanCameron 
```
[ins] r$>  f <- function(x) textshaping::shape_text('x', vjust = x)$shape$y_offset

[ins] r$> f(0)
[1] 0

[ins] r$> f(0.5)
[1] 0
```

**Comment by AllanCameron** [comment]
Thanks for trying that @albert-ying 

From looking at the `shape_text` source code, it is really just an R wrapper round HarfBuzz, which is written in c++. I can't see anything in the `shape_text` source that should be affected by the system you are using, so my guess would be that there is some issue with HarfBuzz, which builds differently according to the system on which it is compiled. You will already have this installed on your computer, but I _think_ that if you were able to update this package, maybe [here](https://launchpad.net/ubuntu/+source/harfbuzz), this may fix your problem.

**Comment by albert-ying** [comment]
Thank you for helping and figuring out the root cause! Although I failed to link the new version of HarfBuzz to `shape_text`... But it is not the problem of `geomtextpath` anymore, I think. Still nice to know what is happing under the hood, thank you so much!
