### ISSUE TITLE
Letter angles when modifying the aspect ratio

### ISSUE THREAD

**Issue by intelligentaccident** [AllanCameron/geomtextpath#6]
This is a very nice little package, and exactly what I was looking for in a particular project I am working on. 

Very briefly, the angle of letters does not appear to handle varying aspect ratios. In the stackoverflow discussion, the angle in the example makes use of scaling with dev_size(), which helps when modifying the scaling of the output. Unless I have overlooked something, this appears not to be included in the package. 

Consider these graphs; output in `trellis.device()` to control aspect ratios, as for e.g. `ggsave()`
``` 
gg1 <- ggplot(data.frame(y = sin(seq(0, pi, length.out = 100)),
                  x = seq(0, pi, length.out = 100),
                  z = 'Pirates vs. Ninjas'), aes(x, y, label = z)) + 
  geom_textpath(hjust = 0.2)`

trellis.device(device="windows", height = 8, width = 8, color=TRUE)
gg1
# Looks fine
trellis.device(device="windows", height = 2, width = 8, color=TRUE)
gg1
# Looks wrong
```

Adding scaling with dev.size() as in the stackoverflow example helps, but is not perfect:
```
.add_path_data <- function (.data) 
{
  grad <- diff(.data$y)/diff(.data$x)
  mult <- diff(range(.data$x))/diff(range(.data$y)) * dev.size()[2] / dev.size()[1]
  .data$grad <- approx(seq_along(grad), grad, seq(1, length(grad), 
                                                  length.out = length(grad) + 1))$y
  .data$angle <- atan(mult*.data$grad) * 180/pi
  .data$angle <- ifelse(sign(c(0, diff(.data$x))) < 0, .data$angle - 
                          180, .data$angle)
  .data$length <- c(0, cumsum(sqrt(diff(.data$x)^2 + diff(mult*.data$y/1)^2)))
  rad_diff <- diff(atan(mult*.data$grad))
  rad_diff <- rad_diff[abs(rad_diff) < pi/2]
  rad_diff <- approx(seq_along(rad_diff), rad_diff, seq(1, 
                                                        length(rad_diff), length.out = nrow(.data) - 1))$y
  curvature <- rad_diff/diff(.data$length)
  effective_length <- diff(.data$length) * (1 + (.data$vjust[1] - 
                                                   0.5) * 0.04 * curvature)
  .data$adj_length <- c(0, cumsum(effective_length))
  .data$string_length <- sapply(.data$label, strwidth, units = "figure")
  .data
}

assignInNamespace(x = '.add_path_data',.add_path_data,ns='geomtextpath')
environment(.add_path_data)<-asNamespace('geomtextpath')
```

However, this does not account for the difference between the device surface and the ggplot panel aspect ratios. 
Ideally, the line
`mult <- diff(range(.data$x))/diff(range(.data$y)) * dev.size()[2] / dev.size()[1]`
should employ the relative aspect ratios of the ggplot panel within the device. Not sure how best to extract those parameters, though.

**Comment by teunbrand** [comment]
Thanks for reporting the issue, it is good to see that people are able to find this package!
We are aware of the aspect ratio / device size issue. I have a fix in mind, but we haven't been able to get to it (yet).
I'll drop an update here once we've got this to work correctly!

**Comment by teunbrand** [comment]
The aspect ratio - text angle issue should now be resolved. Example below:

``` r
library(ggplot2)
library(geomtextpath)

p <- ggplot(data.frame(y = sin(seq(0, pi, length.out = 100)),
                       x = seq(0, pi, length.out = 100),
                       z = 'Pirates vs. Ninjas'), aes(x, y, label = z)) + 
  geom_textpath(hjust = 0.2)

p + theme(aspect.ratio = 2)
```

![](https://i.imgur.com/6IoduCX.png)

``` r
p + theme(aspect.ratio = 0.5)
```

![](https://i.imgur.com/lg0F9ap.png)

<sup>Created on 2021-11-18 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>
