### ISSUE TITLE
Manual textsmoothing?

### ISSUE THREAD

**Issue by johnhenrypezzuto** [AllanCameron/geomtextpath#63]
Hi all,

Thanks for the fantastic package. I'm not sure if this is planning on being implemented but I think some kind of `scale_textsmooth_manual` or a vector of `textsmooth` inputs would be useful idea to keep in mind. It's been an issue that has been coming up for me while I've been using the package. Thank you so much!

**Comment by AllanCameron** [comment]
Hi John. Thanks for adding this issue. At the moment text smoothing is a single - valued parameter and not an aesthetic. I don't think it makes sense to have it as an aesthetic mapping, but vectorised input might be possible. We had not considered this - are you able to provide a motivating example to show where this might be helpful? It would probably require quite a lot of development to allow per-string smoothing, so it would be good to see where it might be useful.

**Comment by teunbrand** [comment]
I agree with Alan here that an evident benefit would be very nice to see. I personally see the text smoothing as a last resort: something you'd use when there are no other methods available anymore. Two scenarios in which that can happen if when you're using a stat that still returns a noisy path, in which case you cannot use `geom_(text)smooth()` or when you're using `geom_textsf()` and it is simply harder to tweak the underlying data. In a worst case scenario, you could still split up the data per path and add individual layers, each with their own text smoothing.

**Comment by AllanCameron** [comment]
I agree Teun - there will always be work-arounds. It might be that there are frequent use cases where it makes sense, but I can't think of them. I'm quite fond of using the text-smoothing rather than seeing it as a last resort - I think many of the community examples I see would benefit from a little bit of text smoothing, but in any case I would definitely want to see a motivating example here.

**Comment by AllanCameron** [comment]
This has been open a while, and no motivating example appears to be forthcoming. Happy to reconsider it later if someone wants to show us where it would be useful.
