### ISSUE TITLE
label border?

### ISSUE THREAD

**Issue by matsutakehoyo** [AllanCameron/geomtextpath#69]
Hi, great work with this packge! 

I just started playing around with it and  was wondering if there is a way to remove the border from geom_labelpath ?

I want to have a background but no border. In geom_label you would achieve this with label.size=0. Alternatively, is there a way to specify border color?

**Comment by teunbrand** [comment]
Hi there,

Yes there are at least 3 ways to do this. One of them is to set the `boxcolour = NA`:

``` r
library(geomtextpath)
#> Loading required package: ggplot2

ggplot(pressure, aes(temperature, pressure)) +
  geom_labelline(label = "Mercury vapor pressure",
                 fill = "cyan", boxcolour = NA)
```

![](https://i.imgur.com/LySll19.png)

<sup>Created on 2022-02-18 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

Two other ways are to:

* Set `boxlinetype = 0`
* Set `boxlinewidth = 0`

Hope this helped!

**Comment by matsutakehoyo** [comment]
Thank you, this is exactly what I was looking for!
