### ISSUE TITLE
geom_textsmooth() doesn't choose method if not explicitly set

### ISSUE THREAD

**Issue by ccsarapas** [AllanCameron/geomtextpath#70]
`geom_smooth()` will choose a default smoothing method if one isn't specified, and `?geom_textpath` says that it will also do this. But it actually issues a warning and returns a blank plot unless a method is explicitly set.
```
library(ggplot2)
library(geomtextpath)

## normal geom_smooth() behavior
ggplot(iris) +
  geom_smooth(
    aes(Sepal.Length, Sepal.Width, color = Species),
    se = FALSE
  )
# `geom_smooth()` using method = 'loess' and formula 'y ~ x'
```
![iris1](https://user-images.githubusercontent.com/84583500/154784148-e323eee2-b925-4a54-96b7-947566ccbfc6.png)
```
## geom_textsmooth() yields warning and blank plot
ggplot(iris) +
  geom_textsmooth(
    aes(Sepal.Length, Sepal.Width, color = Species, label = Species),
    se = FALSE
  )
# `geom_smooth()` using formula 'y ~ x'
# Warning message:
# Computation failed in `stat_smooth()`:
# 'what' must be a function or character string 
```
![iris2](https://user-images.githubusercontent.com/84583500/154784153-af2ca8e3-d97a-47bc-a59b-403926d8445c.png)
```
## setting `method` = "loess" fixes it
ggplot(iris) +
  geom_textsmooth(
    aes(Sepal.Length, Sepal.Width, color = Species, label = Species),
    method = "loess",
    se = FALSE
  )
# `geom_smooth()` using formula 'y ~ x'
```
![iris3](https://user-images.githubusercontent.com/84583500/154784181-dcdb5e45-1141-42eb-a85b-7633ff498ca0.png)

Software details:
```
OS Version: Windows 10 x64 (build 19044)
R Version: R version 4.1.2 (2021-11-01)
ggplot2 Version: 3.3.5
geomtextpath Version: 0.1.0
```

**Comment by teunbrand** [comment]
Hi there,

Thanks for the report, I can indeed confirm there is some kerfuffle around the method argument. I'll try to fix this soon-ish!

**Comment by teunbrand** [comment]
@AllanCameron only tangentially related to this; `geom_textsmooth()` never draws the standard error bands, but when a user sets `se = TRUE`, the position scales get trained with the +/- SE values. Should we just internally set `se = FALSE`?
