### ISSUE TITLE
ggplot2 is separating size and linewidth

### ISSUE THREAD

**Issue by teunbrand** [AllanCameron/geomtextpath#80]
Hey Allan,

The ggplot2 have [separated the size and linewidth](https://github.com/tidyverse/ggplot2/pull/3672) aesthetics. 
Thomas has [posted guidelines on twitter](https://twitter.com/thomasp85/status/1537024892293599235) of potential steps extension developers might take to do the same. 
While we already use the `linewidth` aesthetic almost anywhere, to not conflate the text's `size`, do you think we need to take any action? I'm not too familiar with the `geom_text_sf()` internal workings, but it'd be good to hear if you think it may need to be changed.

Best,
Teun

**Comment by AllanCameron** [comment]
Hi Teun. 

The geom_textsf has separate size and linewidth aesthetics, and I'm pretty sure all the other geoms do too, so I don't think we need to take any specific action here. I guess we could build and test with the dev version of ggplot2, but I think we can safely postpone until the next release.

Regards

Allan

**Comment by teunbrand** [comment]
Yes good points, thanks for confirming!
