### ISSUE TITLE
Can't get things to work

### ISSUE THREAD

**Issue by glorious1** [AllanCameron/geomtextpath#92]
I was excited to find this package, mainly being interested in labeling rivers.  I couldn't get it to print any label text using geom_textsf, though, and it only printed a couple of the actual river features.  The corresponding geom_sf() command included lots of rivers.

Then I tried the example in the help for geom_textsf().  
```
ggplot(waterways) +
 geom_textsf(label = "Forth and Clyde Canal",
              hjust = 0.62, vjust = -0.3, fill = "#E4E0A3") +
 lims(x = c(-4.2, -3.9), y = c(55.9, 56))
```

This printed the line of the canal, but no text.  It also resulted in over 50 warnings:

```
50: In grid.Call.graphics(C_text, as.graphicsAnnot(x$label),  ... :
  no font could be found for family "fallback"
```

I'm using version 0.1.1

Thanks.

**Comment by teunbrand** [comment]
Does switching the graphics device help? E.g. using {ragg} or {svglite}?

**Comment by glorious1** [comment]
Not sure I'm doing it right, but it appears not.
```
> install.packages( "ragg")
library( ragg )
library( geomtextpath )
agg_tiff( filename="maps/canal.png" )
ggplot(waterways) +
  geom_textsf(label = "Forth and Clyde Canal",
              hjust = 0.62, vjust = -0.3, fill = "#E4E0A3") +
  lims(x = c(-4.2, -3.9), y = c(55.9, 56))
```
Result:
```
Warning messages:
1: The text offset exceeds the curvature in one or more paths. This will result in
displaced letters. Consider reducing the vjust or text size, or use the hjust
parameter to move the string to a different point on the path. 
2: The text offset exceeds the curvature in one or more paths. This will result in
displaced letters. Consider reducing the vjust or text size, or use the hjust
parameter to move the string to a different point on the path.  . . . .
```
I couldn't find a map produced anywhere.  Also tried it with agg_png()

**Comment by teunbrand** [comment]
That's about right, but generally you'd include `dev.off()` if you use a device directly. I can reproduce the warning messages, but I'm pretty sure they're just there to warn you that there might be weird curvature. Maybe there should be a way to turn off this warning? The plot doesn't look terrible.

``` r
library( ragg )
library( geomtextpath )
#> Loading required package: ggplot2

file <- tempfile(fileext = ".png")
ragg::agg_png( filename = file)
ggplot(waterways) +
  geom_textsf(label = "Forth and Clyde Canal",
              hjust = 0.62, vjust = -0.3, fill = "#E4E0A3") +
  lims(x = c(-4.2, -3.9), y = c(55.9, 56))
#> Warning: The text offset exceeds the curvature in one or more paths. This will result in
#> displaced letters. Consider reducing the vjust or text size, or use the hjust
#> parameter to move the string to a different point on the path.
#> Warning: The text offset exceeds the curvature in one or more paths. This will result in
#> displaced letters. Consider reducing the vjust or text size, or use the hjust
#> parameter to move the string to a different point on the path.
#> The text offset exceeds the curvature in one or more paths. This will result in
#> displaced letters. Consider reducing the vjust or text size, or use the hjust
#> parameter to move the string to a different point on the path.
#> The text offset exceeds the curvature in one or more paths. This will result in
#> displaced letters. Consider reducing the vjust or text size, or use the hjust
#> parameter to move the string to a different point on the path.
#> The text offset exceeds the curvature in one or more paths. This will result in
#> displaced letters. Consider reducing the vjust or text size, or use the hjust
#> parameter to move the string to a different point on the path.
#> The text offset exceeds the curvature in one or more paths. This will result in
#> displaced letters. Consider reducing the vjust or text size, or use the hjust
#> parameter to move the string to a different point on the path.
#> The text offset exceeds the curvature in one or more paths. This will result in
#> displaced letters. Consider reducing the vjust or text size, or use the hjust
#> parameter to move the string to a different point on the path.
#> The text offset exceeds the curvature in one or more paths. This will result in
#> displaced letters. Consider reducing the vjust or text size, or use the hjust
#> parameter to move the string to a different point on the path.
#> The text offset exceeds the curvature in one or more paths. This will result in
#> displaced letters. Consider reducing the vjust or text size, or use the hjust
#> parameter to move the string to a different point on the path.
dev.off()
#> png 
#>   2
knitr::include_graphics(file)
```

![](https://i.imgur.com/kl1ztsN.png)

<sup>Created on 2023-07-05 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by glorious1** [comment]
Okay, I see, the plot gets generated after dev.off().  So for use for my data, does this mean I need to use ragg and a different graphics device to get it to work?

**Comment by AllanCameron** [comment]
It seems that your default graphics device doesn't have access to the default font used to generate the text. It's a good idea to switch over to ragg anyway in most cases, since it provides very nice antialiasing and much more professional plots. If you are using R studio, you can get the plot previewer to use ragg. In the toolbar at the top of RStudio, select "Tools", then "Global Options..." from the resulting drop-down. In the left-hand pane, select "General", then in the right hand pane click on the "Graphics" button at the top of the window. Now you will have a drop-down giving you the option to change the "Backend" to AGG. Select that, and apply the changes. After a restart, you should get ragg producing your plots in the plotting window.

@teunbrand the multiple curvature warnings _are_ a bit annoying (mea culpa). I will need to see if they can all be caught and combined into a single warning per plot.

**Comment by glorious1** [comment]
Thank you.  Setting the Global Options graphics setting as you suggested enabled me to get the example to work.

I worked for hours to get it to work with my own sf object, a bunch of streams from the US National Hydrography Dataset, Flowlines layer.  I could never get it to print names, either from an aes( label= ) or a literal label setting, as in the example.  

In experimenting, I could see that the streams are not a single continuous line string or multi line string, instead they are often hundreds of very short segments.  I got a length column using st_length() and printed the longest one.  Then I zoomed in on it using lim(), as in your example.  By magnifying the segments in this way I could get names to print for just a few of the longest ones.

Unfortunately, this won’t work in my mapping, which covers several degrees of x and y.  Or, I suppose I could try to somehow fuse the linestrings together by name, so they are long enough to get geom_textsf to print the name?  Many are not named, but I probably don’t need those.

**Comment by AllanCameron** [comment]
@glorious1 yes, I think combining the streams into a single named linestring is the way to go here. Although there is some sf support in geomtextpath, by its nature it requires a bit of manipulation to get a decent result. There's another example [here](https://stackoverflow.com/questions/60086107/automatic-label-placement-for-gis-maps-in-r/60290644#60290644) if that helps

**Comment by glorious1** [comment]
Turns out combining the features by name was easy:
```
R2 <- R %>% group_by( name ) %>% summarize()
```
That got a lot of rivers named.  But, apparently for some other reason, several of the longest rivers in my window still do not get named.

I think it might be because they are multilinestrings instead of linestrings.  Does geom_textsf only work on simple linestrings?  I can’t seem to join the multilinestrings into linestrings.

**Comment by glorious1** [comment]
I finally got it to work.  A visibility filter field I was using was erroneously set to 0 for some short segments of big rivers, the rest of which were set to 5000000 (for maps 1:5000000 and larger).  I was blindly filtering those out, and because the rivers were discontinuous they couldn't be linestrings I guess.  All good now.  Thank you! (The map below is in Washington/Oregon, USA)
![GPMH_terrain](https://github.com/AllanCameron/geomtextpath/assets/6004417/f4c74c3d-f242-448f-9a05-7c1f8a98e0b7)

**Comment by AllanCameron** [comment]
Wow. That's a great result @glorious1

**Comment by glorious1** [comment]
Thanks.  I wonder if you could help me with one related issue.  I'm trying to use vjust and hjust as aesthetics to adjust the label positions individually.  No matter how I do it, the first value in the data column is used for all the labels, and the rest are ignored.  For example
```
 geom_textsf( data=Rc, aes( label=name, hjust=Hjust, vjust=Vjust ) . . .
OR
geom_textsf( data=Rc, aes( label=name ), hjust=Rc$Hjust, vjust=Rc$Vjust . . .
```
The label aesthetic works fine,  but only the first value is used for all vjust/hjust.  Is that a little bug in geomtextpath, or an issue in ggplot2?  It does work with geom_sf_text.
