### ISSUE TITLE
show.legend not working in geom_textabline

### ISSUE THREAD

**Issue by am-lh** [AllanCameron/geomtextpath#96]
Hi,
when using geom_textabline, the show.legend argument does not do anything, but show_guide is. 
However, show_guide is depreciated since ggplot 2.0.0.
It should be safe to align the geomtextpath to this?

NB: great package although, thanks!

**Comment by teunbrand** [comment]
As a reprex:
``` r
library(geomtextpath)
#> Loading required package: ggplot2

df <- data.frame(intercept = c(1, 2), slope = c(1, 2), type = c("A", "B"))

ggplot(df) +
  geom_textabline(
    aes(intercept = intercept, slope = slope, colour = type, label = type),
    show.legend = FALSE
  ) +
  lims(x = c(-5, 5), y = c(-5, 5))
```

![](https://i.imgur.com/JRPQXVY.png)

<sup>Created on 2024-12-10 with [reprex v2.1.1](https://reprex.tidyverse.org)</sup>

Legend should not be there.
